### ISSUE TITLE
Add social stuff whenever a user is returned

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#10]

**Comment by juanmbellini** [comment]
Que te parece esto @lipusal ? Decis que sirve hacerlo?

**Comment by lipusal** [comment]
En principio no me parece, pero no pusiste descripción en el issue, ponele así se sabe qué específicamente estás proponiendo. Igual esto parece ser mucho trabajo así que no creo que se haga

**Comment by juanmbellini** [comment]
La idea es que cada ver que pedis un User al backend (ya sea pidiendo especificamente el user a **/Users/:id**, o por username/email), o cuando, por ejemplo, pedis un thread y te viene su **creator**, obteniendo toda la data social del creator de un thread.

**Comment by lipusal** [comment]
Hasta ahí ya entiendo, pero a qué llamás "data social"? No tenemos ningún sistema social más que a cuánta gente seguís y cuánta gente te sigue, y deberíamos implementar todo un sistema social para que la información sea útil. Me parece que sería demasiado trabajo implementar todo ese sistema social

**Comment by juanmbellini** [comment]
Claro, o sea, que devuelva seguidores y seguidos y esas cosas (además de lo que es datos del usuario en sí)

**Comment by lipusal** [comment]
Ok, pero qué valor agregado tiene? La cantidad de seguidores sólo la mostramos en el perfil, dónde más proponés mostrarla? Qué información extra proponés mostrar, if any? Dónde se mostraría? Explayate en eso para ver si vale la pena o no

**Comment by juanmbellini** [comment]
Más que nada era para mantener consistente la API, la verdad no es algo necesario en sí

**Comment by lipusal** [comment]
Entonces me parece al pedo, porque igual esa info no la vamos a mostrar en ningún lado.
Closing. Si se me ocurre alguna situación en la que me parezca piola vuelvo a abrir el issue.
