### ISSUE TITLE
Javadoc says that this method returns something but signature says it returns void

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#108]
https://github.com/juanmbellini/PowerUp/blob/b33be571da80c20a76198d3e227a9e1d0cfe5b05/paw-webapp/model/src/main/java/ar/edu/itba/paw/webapp/model/User.java#L129

https://github.com/juanmbellini/PowerUp/blob/b33be571da80c20a76198d3e227a9e1d0cfe5b05/paw-webapp/model/src/main/java/ar/edu/itba/paw/webapp/model/User.java#L135

**Comment by juanmbellini** [comment]
@lipusal Que te parece esto? Método similar retorna el objeto de relationship, pero éste no
https://github.com/juanmbellini/PowerUp/blob/b33be571da80c20a76198d3e227a9e1d0cfe5b05/paw-webapp/model/src/main/java/ar/edu/itba/paw/webapp/model/User.java#L168

Por otro lado, esto se usa para la game list de usuarios. El problema es que no se que hacer con el testing.

**Comment by lipusal** [comment]
Alcanza con cambiar la documentación del método de User, sacándole que devuelve eso. Todo lo demás parece que anda, por qué es un bug?

**Comment by juanmbellini** [comment]
Le puse bug porque no hace lo que dice que hace. Pero sí, es cambiar la doc
