### ISSUE TITLE
Add filter pagination

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#11]

**Comment by juanmbellini** [comment]
@lipusal Necesitas esto?

**Comment by lipusal** [comment]
Sí, la paginación de los filtros para no sobrecargar el server
Para que ande esto vamos a tener que ir un par de horas antes a patricios y ponernos en una compu que ande bien
Si se hace la prueba desde otra compu puede que no ande para nada bien...no sé qué alternativa tenemos
Si hacemos que los filtros sean su propio endpoint no mejora mucho, es más laburo para nosotros y va a andar igual de lento

**Comment by juanmbellini** [comment]
Descubrí que el problema no era la sobrecarga por cantidad de elementos, sino que estaba mal implementada la parte de persistencia que se encargaba de esto.

Igualmente, en la PR #161 te incluyo paginación, aunque el problema groso era lo que te dije. Por cada ```Company```, se fijaba si era developer/publisher, y por lo tanto, se generaban N queries. Teniendo más de 20mil Companies, esto era muy pesado. Ahora se hace con inner joins entre la tabla de companies y la tabla que guarda companies que son developers/publishers, teniendo una única query.

**Comment by lipusal** [comment]
Qué buena noticia!
