### ISSUE TITLE
Test fails randomly in Travis

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#116]
Random numbers generated in [this test](https://github.com/juanmbellini/PowerUp/blob/master/paw-webapp/model/src/test/java/ar/edu/itba/paw/webapp/model/ReviewTest.java#L702) are sometimes failing, forcing us to re-run certain Travis builds, eg. https://travis-ci.org/juanmbellini/PowerUp/builds/288225596#L2661

We should either use appropriate random numbers or stick to arbitrary but FIXED numbers for tests.

**Comment by juanmbellini** [comment]
jajaj justo ese build pasa

**Comment by juanmbellini** [comment]
Dejame que veo bien que onda el método

**Comment by lipusal** [comment]
Sí, porque le hice restart dos veces! Pensé que cambiaría el número de build pero parece que no

**Comment by juanmbellini** [comment]
creo que te pone 154.1 o 154.2 etc

**Comment by juanmbellini** [comment]
aaah nono, eso es cuando haces un amend commit y force pusheas
