### ISSUE TITLE
Use bigger pictures in lightbox

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#12]
See https://bitbucket.org/itba/paw-2016b-02/pull-requests/198

**Comment by juanmbellini** [comment]
Qué onda este issue @lipusal ??
Se hace o que onda?

**Comment by juanmbellini** [comment]
Que onda con esto @lipusal ?

**Comment by lipusal** [comment]
Lo voy a ver después, si no se llega lo cierro cuando esté seguro

**Comment by lipusal** [comment]
Addressed by a6348068f31b3773a6ab15ce7ee81dfa6be25bc4

**Comment by juanmbellini** [comment]
👍 
Después fijate que onda si hay que cerrarlo

**Comment by lipusal** [comment]
Sí, le agregué el `Closes ...` así lo auto-cierra cuando se mergee
