### ISSUE TITLE
Agregar info de usuario PAW en el README

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#127]
El enunciado dice:

> En caso de que la aplicacón requiera algún tipo de autenticación para
accederla, debe existir un archivo README.md que indique claramente
credenciales para al menos un usuario con cada nivel de acceso
existente en la aplicación.

La primera migración que se corre sola agrega al usuario `paw` con contraseña `paw`. Habría que ponerlo como un datito en el README, aunque no hace falta autenticarse para usar la aplicación.

**Comment by juanmbellini** [comment]
Podríamos agregar un manual de usuario sino (el readme te dice como instalarla)
Podríamos agregar, sino, un tutorial en la app que diga cómo usar la app.

**Comment by lipusal** [comment]
No hace falta manual de usuario, alcanza con instrucciones de cómo instalar la aplicación; sólo armé este issue por lo que leí del enunciado

**Comment by juanmbellini** [comment]
bueno, entonces que hacemos?

**Comment by lipusal** [comment]
Agregar una nota en el README que diga que para comentar/likear/etc. hace falta registrarse, y que por default se incluye un usuario `paw` con contraseña `paw` que ya tiene algo de data cargada, se puede usar esa cuenta como cuenta de test.

**Comment by juanmbellini** [comment]
okey
