### ISSUE TITLE
Check if CORS stuff is implemented in GameJerseyController

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#129]
Me parece que falta el método con ```@Options``` para todos los métodos del controller.
https://github.com/juanmbellini/PowerUp/blob/master/paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/GameJerseyController.java

**Comment by lipusal** [comment]
No hace falta porque el preflight (el mandar un OPTIONS antes de hacer la request posta) no hace falta para GETs ([source](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#How_CORS_works)) que es lo único que hay para games.
Si me estoy equivocando, de todas maneras sé que no hace falta porque todo lo de games anda localmente, con la API en un puerto y la página en otro.
