### ISSUE TITLE
Delete `deploy` branch?

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#135]

**Comment by lipusal** [comment]
Creo que ya no hace falta más la branch `deploy`, desde hace meses que estoy deployando directo desde `master`. Después me pongo a ver qué diff tiene con master a ver si tiene algo para rescatar, sino borro la branch.

**Comment by lipusal** [comment]
Sólo había diferencias que no tenían que ver con deploy así que la borré. Closing.

**Comment by lipusal** [comment]
Mentira, no pude porque está protegida. Podés sacarle la protección y borrarla? Te lo asigno

**Comment by juanmbellini** [comment]
Listo, ya está desprotegida

**Comment by lipusal** [comment]
Arigatou, listo
