### ISSUE TITLE
Password reset doesn't work

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#15]
Clicking the "Forgot Password?" link in the Login page sends the email correctly, but the new password sent in the email is not recognized. The login page says "invalid username/password" and users are locked out of their account.

## TODO
- [x] Assign jul when he gets in the repo

**Comment by juanmbellini** [comment]
Que te parece si en vez de mandar una clave nueva, mandamos un link? Deberíamos tener una tabla de links (encriptados?), junto con el timestamp y la duración del dicho link.

**Comment by juanmbellini** [comment]
Creo que el bug viene de esto:
https://github.com/juanmbellini/PowerUp/blob/9d60b36295dcf457ea8c11c752f58afca4eb8078/paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java#L177

O sea, se le pide al service que genere una password nueva random, dsp el controller la hashea, y dsp se la pasa al service (que espera passwords en plano).
Nota: Está logica igualmente (generar una nueva password y despues cambiarla) debería estar solo en el service. El controller solo tiene que tomar el llamado y pasarlo al service directamente.
