### ISSUE TITLE
Improve profile picture stuff

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#154]
Needed to check whether a user has a profile picture or not, and to conditionally show the `Delete your profile picture` in the Profile page.  Also consider making picture deletion idempotent (ie. if the user already doesn't have a picture, don't fail)

**Comment by juanmbellini** [comment]
- [x] Add profilePictureUrl field in User json
- [x] Return 404 in case no picture
- [x] Make delete picture idempotent
