### ISSUE TITLE
Only allow expanding comments with replies

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#18]
When the thread comments were re-implemented with the new frontend, the API did not return reply count for comments. Because of this, all comments show a "Load replies" link, regardless of whether they actually have replies.  Now that the API does bring this information, we should account for it and only show this link for comments that have replies.

**Comment by juanmbellini** [comment]
Se puede cerrar el issue?

**Comment by lipusal** [comment]
🤔 se supone que se debería haber cerrado solo, la descripción de #20 empieza con "Resolves #18" (que verás que está subrayado), la documentación decía que lo cerraba solo. Quizá había que usar otra palabra, pero sí, lo cierro.
