### ISSUE TITLE
Home page is missing

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#2]
When getting into the home page, nothing is displayed

**Comment by lipusal** [comment]
Querés decir que el feed está vacío no? Esto pasa cuando no seguís a nadie porque tu feed está vacío. Mínimo debería decirte que está vacío. @Drocheg lo vas a arreglar antes de irte?

**Comment by juanmbellini** [comment]
Si, pero si no seguís a nadie debería decir algo... además para mi el home no debería ser solo el feed. Faltarían recomendaciones y cosas así por ejemplo

**Comment by lipusal** [comment]
Fixed by c337e0bdaf2d20a11db5fe07cbfeb18691dbebd5. El feed está vacío si no seguís a nadie, pero ese es otro issue.
