### ISSUE TITLE
Clicking the logo doesn't do anything

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#3]
When clicking the logo in the navbar, nothing happens. It should be a link to the home page.

**Comment by lipusal** [comment]
Dónde no anda? A mí me anda siempre, incluso en mobile (pero la página NO está hecha para mobile)

Ejemplo: 
![a](https://user-images.githubusercontent.com/5761629/29498279-add2d6b6-85ce-11e7-91d1-eb1d47b121c0.gif)

**Comment by juanmbellini** [comment]
En pawserver no me anda a mí (google chrome)

**Comment by lipusal** [comment]
A mí me anda desde todas las páginas, en staging y prod, podés volver a probar?

**Comment by juanmbellini** [comment]
Que onda esto? Se puede cerrar el issue?

**Comment by juanmbellini** [comment]
Ya probe en pawserver ahora y anda
