### ISSUE TITLE
Consider creating API documentation in project's wiki

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#31]

**Comment by juanmbellini** [comment]
Cerramos esto @lipusal ?

**Comment by lipusal** [comment]
Muy nice to have pero sólo nos interesaría a vos y a mí y no ganamos nada en la nota. Después de la entrega lo podemos probar for the lulz con Swagger o algo así si querés. Como no lo vamos a hacer para la entrega, cierro.
