### ISSUE TITLE
Delete all references to user's removal

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#33]
Up to now, we can't delete (or disable users). Will this be left like this?

**Comment by lipusal** [comment]
Yes, deleting or disabling accounts is not necessary for our project and implementing it would require new endpoints and new pages on the frontend, all work that can be allotted to higher-priority tasks.

**Comment by juanmbellini** [comment]
Lo vuelvo a abrir para eliminar todo lo que haga referencia a eliminar usuarios (código comentado)
