### ISSUE TITLE
Can this be deleted?

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#37]
https://github.com/juanmbellini/PowerUp/blob/80f700b355a0d580b4b37d523d9d81ca00766ec0/paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/el/Functions.java#L1

I think this is not used any more.

**Comment by lipusal** [comment]
Sí se puede borrar, se usaba para armar el árbol recursivo de comments y sus replies cuando usabamos JSPs

**Comment by juanmbellini** [comment]
Ok, aceptame la PR #51
