### ISSUE TITLE
This should be moved to Service layer

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#38]
https://github.com/juanmbellini/PowerUp/blob/80f700b355a0d580b4b37d523d9d81ca00766ec0/paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/el/Functions.java#L1

I think this is not used any more.

**Comment by lipusal** [comment]
Esto no hay que moverlo, hay que borrarlo como dice #37

**Comment by juanmbellini** [comment]
Creo que me equivoque de link cuando arme este issue
