### ISSUE TITLE
Decide what to do about returning part of the description

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#39]
https://github.com/juanmbellini/PowerUp/blob/80f700b355a0d580b4b37d523d9d81ca00766ec0/paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/dto/GameDto.java#L110

**Comment by lipusal** [comment]
Te había pedido que NO me lo cortes, mandamelo entero que yo lo corto por CSS en el front. En una Mac puede que te entre más texto que en Linux o en Windows por la resolución, así que no cortes el texto. Mandalo entero.

**Comment by juanmbellini** [comment]
Dale dale, entonces le saco esto.
