### ISSUE TITLE
Remove escapeUnsafeCharacters from GameServiceImpl

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#40]
https://github.com/juanmbellini/PowerUp/blob/80f700b355a0d580b4b37d523d9d81ca00766ec0/paw-webapp/service/src/main/java/ar/edu/itba/paw/webapp/service/GameServiceImpl.java#L45

There is a method to escape unsafe characters. I don't think this is necessary

**Comment by lipusal** [comment]
Ahora que tenemos Angular creo que no, después probamos sacandolo y vemos qué onda.

**Comment by juanmbellini** [comment]
Dale, dsp de testear me meto con estas cosas

**Comment by lipusal** [comment]
No mentira, esto no es del backend para el front, es del frontend para el back. Esto creo que era antes de que usemos prepared statements, entonces si vos buscabas algo con `%` por ejemplo podía matchear muchas cosas en SQL. Probá sacarlo y fijarte si da lo mismo (ej. podés hacer un test).

**Comment by juanmbellini** [comment]
No creo que haga falta. Me imagino que Jersey ya te cura las cosas (los % los cambia adecuadamente).
Respecto a SQL se supone que Hibernate te cubre frente a sql injection.

**Comment by lipusal** [comment]
Probá, me imagino que por algo estaba antes

**Comment by juanmbellini** [comment]
Al final, esto era para la búsqueda en la base de datos. Si no se escapan, te matchea todo cuando le metes un ```%```.
