### ISSUE TITLE
Main README is missing some details

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#5]
- Step 3, creating a DB, should either specify a username or mention that said username will be the same as the one in step 6
- Idem step 4
- Step 6 should mention the exact `.properties` file name since the app only picks up certain files (common.properties, development.properties, production.properties, passwords.properties)
- Passwords (JWT secret, email password, DB password) should be in passwords.properties and other configs in common.properties

**Comment by lipusal** [comment]
We should also mention, common and passwords.properties are required, development and production are not, they are evaluated in the following order and properties that are in multiple files get overridden by the LAST file read:

- common.properties
- passwords.properties
- production.properties
- development.properties

**Comment by juanmbellini** [comment]
Listo
