### ISSUE TITLE
Remove review references from Game class

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#62]
https://github.com/juanmbellini/PowerUp/blob/dce065c67dee4eabc70b8f5b800d4e824106f159/paw-webapp/model/src/main/java/ar/edu/itba/paw/webapp/model/Game.java#L64

There is a property definition in ```Game``` model that is commented.
Can be removed?

**Comment by lipusal** [comment]
Es sacar todo  lo que sea reviews de `Game`? No tiene sentido tener este mapeo a nivel modelo, ya que están relacionados? Cómo conseguimos las reviews de un juego ahora? Directamente desde un service?

**Comment by juanmbellini** [comment]
Estas relacionados, pero no se usa para nada el mapeo
