### ISSUE TITLE
Remove Game setters and adders

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#63]
https://github.com/juanmbellini/PowerUp/blob/dce065c67dee4eabc70b8f5b800d4e824106f159/paw-webapp/model/src/main/java/ar/edu/itba/paw/webapp/model/Game.java#L206

https://github.com/juanmbellini/PowerUp/blob/dce065c67dee4eabc70b8f5b800d4e824106f159/paw-webapp/model/src/main/java/ar/edu/itba/paw/webapp/model/Game.java#L234

Game does not change after creation (except avgScore, which can be updated)

**Comment by lipusal** [comment]
👍 , hacelo después

**Comment by juanmbellini** [comment]
@lipusal Me pongo a hacer esto a ver si quedan métodos para testear del ```Game```.
