### ISSUE TITLE
Add frontend build caches to Travis config

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#79]
This must be done once dev and chore/travis are merged into master

**Comment by lipusal** [comment]
Qué era esto? Ponerle que cachee `node_modules`,  etc?

**Comment by juanmbellini** [comment]
Sisi, que cachee todo lo que se usa en el front que se pueda guardar para no volver a hacerlo

**Comment by lipusal** [comment]
Veo que ya está `node_modules`, etc. en el `travis.yml`.  Qué hace falta? Se puede cerrar esto?

**Comment by juanmbellini** [comment]
No se que más hace falta, no se bien como funcionan todas las build tools del front. Por eso te había asignado a vos a ver si había algo más para cachear.

Si no hay más para cachear, cerramos el issue
