### ISSUE TITLE
Delete `dabatase` folder

### ISSUE THREAD

**Issue by lipusal** [juanmbellini/PowerUp#83]
The folder is unused (initial migrations are now incorporated into flyway) and throws off the language percentage in the repo
<img width="990" alt="screen shot 2017-10-02 at 6 14 47 pm" src="https://user-images.githubusercontent.com/5761629/31099801-9c093cd6-a79d-11e7-9633-efc63d3fb931.png">

@juanmbellini si lo querés hacer, asignate

**Comment by juanmbellini** [comment]
Sisi, lo tenia pensado.
Tambien hay que borrar la carpeta test
