### ISSUE TITLE
Profile page says that I have one game in the game list, but when visiting the game list page (from the nav bar) the list has a different amount of games

### ISSUE THREAD

**Issue by juanmbellini** [juanmbellini/PowerUp#92]

**Comment by lipusal** [comment]
Screenshots plz?

**Comment by juanmbellini** [comment]
Como hago para filmar la pantalla y mandar gif?

**Comment by lipusal** [comment]
Alcanza con 2-3 screenshots, pero sino bajate LICEcap
Después para asegurarte que sube la GIF como animada no le podés hacer drag-and-drop al textbox de comentario, tenés que apretar el link de abajo del textbox que dice `selecting them` y la seleccionás de ahí
